- hosts: "{{ hosts }}"
  gather_facts: yes
  sudo: yes

- hosts: monitors
  sudo: yes

  vars_files:
   - vars/main.yml
   - vars/icinga2_services.yml
   - vars/icinga2_commands.yml
   - vars/icinga2_user_contacts.yml
   - group_vars/{{ hosts }}

  tasks:

   - include: tasks/icinga2_add_services.yml
   - include: tasks/icinga2_add_commands.yml
   - include: tasks/icinga2_add_users.yml
   - include: tasks/icinga2_add_host.yml

  handlers:

   - include: handlers/handlers.yml
