---
- name: Install Icinga2 New Web Classic on CentOS OS family
  yum: name={{ item.package }} state=latest
  with_items: icinga2_new_web_pkg
  notify:
   - restart apache

- name: Create the Database for Icinga Web Classic on CentOS OS family
  mysql_db: name={{ icinga2_web_db }}
            state=present
  register: icinga2_web_db_state

- name: Import the Icinga Web Schema for Icinga2 on CentOS OS family (only when the database is created for the first time)
  mysql_db: name={{ icinga2_web_db }}
            state=import
            target={{ icinga2_web_mysql_schema }}
  when: icinga2_web_db_state|changed

- name: Configure Grants on Icinga Web Database on CentOS OS family (here we use same password as icinga2_ido_db_user_pass to avoid confusion)
  mysql_user: name={{ icinga2_web_db_user }}
              password={{ icinga2_web_db_user_pass }}
              state=present
              priv="{{ icinga2_web_db }}.*:SELECT,INSERT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Enable Icinga2 features on CentOS OS family
  command: /usr/sbin/icinga2-enable-feature "{{ item.feature }}"
  with_items: features
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2

- name: Configure Icinga Web Command Access on CentOS OS family
  template: src={{ item.template }}
            dest={{ item.conf }}
  with_items: icinga2_new_web_confs
  notify:
   - restart icinga2
   - icinga-web-clearcache

- name: Icinga New Web Classic Installation finished (CentOS)
  debug: msg="Now you can login at http://{{ ansible_eth0.ipv4.address }}/icinga-web with username root and password password"
