---
- name: Install IDO Mysql on CentOS OS family
  yum: name={{ item.package }} state=latest
  with_items: icinga2_ido_mysql

- name: Install Mysql Server on CentOS OS family
  yum: name={{ item.package }} state=latest
  with_items: icinga2_mysql_pkg

- name: Start Mysql Server on CentOS OS family
  service: name={{ mysql_server }} state=started enabled=yes

- name: Create the Database for IDO on CentOS OS family
  mysql_db: name={{ icinga2_ido_db }}
            state=present
  register: icinga2_db_ido

- name: Import the IDO Schema for Icinga2 on CentOS OS family (only when the database is created for the first time)
  mysql_db: name={{ icinga2_ido_db }}
            state=import
            target={{ icinga2_ido_mysql_schema }}
  when: icinga2_db_ido|changed

- name: Configure Grants on Icinga Database on CentOS OS family
  mysql_user: name={{ icinga2_ido_db_user }}
              password={{ icinga2_ido_db_user_pass }}
              state=present
              priv="{{ icinga2_ido_db }}.*:SELECT,INSERT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Configure IDO Mysql Feature on CentOS OS family
  template: src={{ item.template }}
            dest={{ item.conf }}
  with_items: icinga2_ido_mysql
  notify:
   - restart icinga2
