- name: Install Icinga classicgui for CentOS OS family
  yum: name={{ item.package }} state=latest
  with_items: icinga2_web_pkg
  notify:
   - restart icinga2
   - restart apache

- name: Icinga Classic Gui Installation finished (CentOS)
  debug: msg="Now you can login at http://{{ ansible_eth0.ipv4.address }}/icinga with username icingaadmin and password icingaadmin"
