- name: Copy Host Definitions
  template: src=host_def.j2 
            dest={{ icinga2_hosts_dir }}monitored_hosts.conf
            owner=root 
            group=root 
            mode=0644
  notify:
   - restart icinga2
