---
- name: Configure Debconf values for Icinga Common (required for Icinga Web) on Debian OS family
  debconf: name={{ item.name }}
           question={{ item.question }}
           value={{ item.value }}
           vtype={{ item.vtype }}
  with_items: icinga2_icinga_common

- name: Configure Debconf values for Icinga Web on Debian OS family
  debconf: name={{ item.name }}
           question={{ item.question }}
           value={{ item.value }}
           vtype={{ item.vtype }}
  with_items: icinga2_icinga_web

- name: Install Icinga Web on Debian OS family
  apt: pkg={{ item.package }} 
       update_cache=yes
       state=latest
  with_items: icinga2_new_web_pkg

- name: Icinga Web Installation finished
  debug: msg="Now you can login at http://{{ ansible_eth0.ipv4.address }}/icinga-web with username root and the password you provided"
