---
# tasks file for icinga2-ansible

- name: Include OS specific variables
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"

- include: icinga2_install_Debian.yml
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

- include: icinga2_install_Ubuntu.yml
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- include: icinga2_install_RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- include: icinga2_install_Fedora.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'

- include: icinga2_install_Suse.yml
  when: ansible_os_family == 'Suse'
