---
# handlers file for icinga2-ansible

- name: restart icinga2
  service: name=icinga2 
           state=restarted 
           enabled=yes

- name: reload icinga2
  service: name=icinga2  
           state=reloaded 
           enabled=yes

- name: restart apache
  service: name={{ apache }} 
           state=restarted 
           enabled=yes

- include: firewalld.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Fedora'
